[family]
name = 'BBS+'
color = '0B346E'
color2 = '7DB9DE'
marker = '+'
url = 'https://eprint.iacr.org/2023/275'

[set]

[set.1]
name = 'BBS+'
#public_key_bytes = 1312
#signature_bytes = 2420
security_level = 1


