[family]
name = 'ECDSA'
color = 'FF5370'

[set]

[set.256]
name = 'ECDSA-256'
public_key_bytes = 32
signature_bytes = 64
security_level = 1

[set.7680]
name = 'ECDSA-384'
public_key_bytes = 48
signature_bytes = 96
security_level = 3

[set.15360]
name = 'ECDSA-512'
public_key_bytes = 64
signature_bytes = 128
security_level = 5



